/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiziServiceSlugRouteImport } from './routes/servizi.$serviceSlug'
import { Route as ServiziRouteImport } from './routes/servizi.'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziServiceSlugRoute = ServiziServiceSlugRouteImport.update({
  id: '/servizi/$serviceSlug',
  path: '/servizi/$serviceSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi/',
  path: '/servizi/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/servizi/': typeof ServiziRoute
  '/servizi/$serviceSlug': typeof ServiziServiceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/servizi': typeof ServiziRoute
  '/servizi/$serviceSlug': typeof ServiziServiceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/servizi/': typeof ServiziRoute
  '/servizi/$serviceSlug': typeof ServiziServiceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/servizi/' | '/servizi/$serviceSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/servizi' | '/servizi/$serviceSlug'
  id: '__root__' | '/' | '/servizi/' | '/servizi/$serviceSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ServiziRoute: typeof ServiziRoute
  ServiziServiceSlugRoute: typeof ServiziServiceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi/$serviceSlug': {
      id: '/servizi/$serviceSlug'
      path: '/servizi/$serviceSlug'
      fullPath: '/servizi/$serviceSlug'
      preLoaderRoute: typeof ServiziServiceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi/': {
      id: '/servizi/'
      path: '/servizi'
      fullPath: '/servizi/'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ServiziRoute: ServiziRoute,
  ServiziServiceSlugRoute: ServiziServiceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
